name: job-level-custom-evn
on: [push]
jobs:
  sample-job-1:
      env:
        dish: Samsa is available
      runs-on: ubuntu-latest
      steps:
        - name: step-1
          run: echo "${dish}"
          
        - name: step-2
          run: echo "${dish}"
          
  sample-job-2:
      runs-on: ubuntu-latest
      steps:
        - run: echo "${dish}"
